components:
  schemas:
    Schema5:
      name: John
      id: '105'
    Schema6:
      name: Julie
      id: '106'
    Schema3:
      name: Alice
      id: '111'
  messages:
    Event6:
      payload:
        $ref: '#/components/schemas/Schema6'
      description: ''
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
    Event3:
      payload:
        $ref: '#/components/schemas/Schema3'
      description: ''
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
    Event5:
      payload:
        $ref: '#/components/schemas/Schema5'
      description: ''
      schemaFormat: application/vnd.aai.asyncapi+json;version=2.0.0
      contentType: application/json
channels:
  test/supply/orders/4:
    publish:
      message:
        $ref: '#/components/messages/Event5'
  test/supply/orders/5:
    publish:
      message:
        $ref: '#/components/messages/Event6'
  test/supply/orders/2:
    publish:
      message:
        $ref: '#/components/messages/Event3'
asyncapi: 2.0.0
info:
  description: ''
  title: Application5
  version: 0.0.1
